//
//  ConstantStrings.h
//  YawiiB
//
//  Created by wenqing zhou on 10/27/12.
//  Copyright (c) 2012 Yawii. All rights reserved.
//

FOUNDATION_EXPORT NSString *const WEBSERVICE_BASE_URL;
FOUNDATION_EXPORT NSString *const WEBSERVICE_BASE_DEV_URL;

FOUNDATION_EXPORT NSString *const APP_COMPANY;

FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_CONTENT;
FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_ORIGINAL;
FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_CURRENT;
FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_VALIDTIME;
FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_VALIDNUMBER;

FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_ADDRESS;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_CITY;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_COUNTRYCODE;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_CURRENCYCODE;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_NAME;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_PHONE;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_URL_LOGO;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_POSTALCODE;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_URL_LOGO_LOCAL;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_HID;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_KEY;

FOUNDATION_EXPORT NSString *const NEWSPECIAL_DICT_DISCOUNT;
FOUNDATION_EXPORT NSString *const ACCOUNT_DICT_USER_LOGINED;

